-- Complex Snowflake-style financial schema used to test the semantic-modeling skill.
-- The physical tables deliberately include role-playing parties, multiple date bases,
-- snapshot balances, non-additive prices/rates, and ontology-aligned financial terms.

CREATE SCHEMA IF NOT EXISTS MART_FINANCE;

CREATE OR REPLACE TABLE MART_FINANCE.LEGAL_ENTITY (
  LEI VARCHAR NOT NULL,
  LEGAL_NAME VARCHAR NOT NULL,
  JURISDICTION VARCHAR,
  ENTITY_STATUS VARCHAR,
  ENTITY_TYPE VARCHAR,
  PARENT_LEI VARCHAR,
  EFFECTIVE_FROM_DATE DATE,
  EFFECTIVE_TO_DATE DATE
);

CREATE OR REPLACE TABLE MART_FINANCE.INSTRUMENT_MASTER (
  INSTRUMENT_ID VARCHAR NOT NULL,
  ISIN VARCHAR,
  CUSIP VARCHAR,
  FIGI VARCHAR,
  ISSUER_LEI VARCHAR,
  OBLIGOR_LEI VARCHAR,
  INSTRUMENT_TYPE VARCHAR,
  SECURITY_DESCRIPTION VARCHAR,
  CURRENCY_CODE VARCHAR,
  COUPON_RATE NUMBER(18, 8),
  MATURITY_DATE DATE,
  ISSUE_DATE DATE,
  IS_CALLABLE BOOLEAN,
  IS_FLOATING_RATE BOOLEAN
);

CREATE OR REPLACE TABLE MART_FINANCE.POSITION_SNAPSHOT (
  POSITION_ID VARCHAR NOT NULL,
  ACCOUNT_ID VARCHAR NOT NULL,
  PORTFOLIO_ID VARCHAR NOT NULL,
  INSTRUMENT_ID VARCHAR NOT NULL,
  CUSTODIAN_LEI VARCHAR,
  AS_OF_DATE DATE NOT NULL,
  QUANTITY NUMBER(38, 8),
  BOOK_VALUE_LOCAL NUMBER(38, 6),
  MARKET_VALUE_LOCAL NUMBER(38, 6),
  MARKET_VALUE_USD NUMBER(38, 6),
  ACCRUED_INTEREST_USD NUMBER(38, 6),
  UNREALIZED_GAIN_LOSS_USD NUMBER(38, 6)
);

CREATE OR REPLACE TABLE MART_FINANCE.TRADE (
  TRADE_ID VARCHAR NOT NULL,
  INSTRUMENT_ID VARCHAR NOT NULL,
  BUYER_LEI VARCHAR,
  SELLER_LEI VARCHAR,
  BROKER_LEI VARCHAR,
  COUNTERPARTY_LEI VARCHAR,
  TRADE_DATE DATE NOT NULL,
  SETTLEMENT_DATE DATE,
  TRADE_STATUS VARCHAR,
  SIDE VARCHAR,
  QUANTITY NUMBER(38, 8),
  PRICE NUMBER(38, 10),
  NOTIONAL_AMOUNT_USD NUMBER(38, 6),
  COMMISSION_USD NUMBER(38, 6)
);

CREATE OR REPLACE TABLE MART_FINANCE.MARKET_PRICE (
  INSTRUMENT_ID VARCHAR NOT NULL,
  PRICE_DATE DATE NOT NULL,
  PRICE_TYPE VARCHAR NOT NULL,
  BID_PRICE NUMBER(38, 10),
  ASK_PRICE NUMBER(38, 10),
  MID_PRICE NUMBER(38, 10),
  CLOSE_PRICE NUMBER(38, 10),
  SOURCE_SYSTEM VARCHAR
);

CREATE OR REPLACE TABLE MART_FINANCE.FX_RATE (
  RATE_DATE DATE NOT NULL,
  FROM_CURRENCY_CODE VARCHAR NOT NULL,
  TO_CURRENCY_CODE VARCHAR NOT NULL,
  SPOT_RATE NUMBER(38, 12),
  SOURCE_SYSTEM VARCHAR
);

CREATE OR REPLACE TABLE MART_FINANCE.RISK_EXPOSURE (
  EXPOSURE_ID VARCHAR NOT NULL,
  INSTRUMENT_ID VARCHAR NOT NULL,
  COUNTERPARTY_LEI VARCHAR,
  EXPOSURE_DATE DATE NOT NULL,
  EXPOSURE_TYPE VARCHAR,
  EXPOSURE_AMOUNT_USD NUMBER(38, 6),
  VAR_95_1D_USD NUMBER(38, 6),
  DURATION_YEARS NUMBER(18, 8),
  CREDIT_RATING VARCHAR,
  RISK_MODEL_VERSION VARCHAR
);

CREATE OR REPLACE VIEW MART_FINANCE.VW_INSTRUMENT_ENRICHED AS
SELECT
  i.INSTRUMENT_ID,
  i.ISIN,
  i.CUSIP,
  i.FIGI,
  i.INSTRUMENT_TYPE,
  i.SECURITY_DESCRIPTION,
  i.CURRENCY_CODE,
  i.COUPON_RATE,
  i.MATURITY_DATE,
  i.ISSUE_DATE,
  i.IS_CALLABLE,
  i.IS_FLOATING_RATE,
  i.ISSUER_LEI,
  issuer.LEGAL_NAME AS ISSUER_NAME,
  issuer.JURISDICTION AS ISSUER_JURISDICTION,
  i.OBLIGOR_LEI,
  obligor.LEGAL_NAME AS OBLIGOR_NAME,
  DATEDIFF('day', CURRENT_DATE(), i.MATURITY_DATE) AS DAYS_TO_MATURITY
FROM MART_FINANCE.INSTRUMENT_MASTER i
LEFT JOIN MART_FINANCE.LEGAL_ENTITY issuer
  ON i.ISSUER_LEI = issuer.LEI
LEFT JOIN MART_FINANCE.LEGAL_ENTITY obligor
  ON i.OBLIGOR_LEI = obligor.LEI;

CREATE OR REPLACE VIEW MART_FINANCE.VW_POSITION_VALUATION AS
SELECT
  p.POSITION_ID,
  p.ACCOUNT_ID,
  p.PORTFOLIO_ID,
  p.INSTRUMENT_ID,
  p.CUSTODIAN_LEI,
  p.AS_OF_DATE,
  p.QUANTITY,
  p.BOOK_VALUE_LOCAL,
  p.MARKET_VALUE_LOCAL,
  p.MARKET_VALUE_USD,
  p.ACCRUED_INTEREST_USD,
  p.UNREALIZED_GAIN_LOSS_USD,
  i.INSTRUMENT_TYPE,
  i.CURRENCY_CODE,
  i.ISSUER_LEI,
  i.ISSUER_NAME,
  i.OBLIGOR_LEI,
  i.MATURITY_DATE,
  p.MARKET_VALUE_USD - p.BOOK_VALUE_LOCAL AS VALUE_OVER_BOOK_USD
FROM MART_FINANCE.POSITION_SNAPSHOT p
LEFT JOIN MART_FINANCE.VW_INSTRUMENT_ENRICHED i
  ON p.INSTRUMENT_ID = i.INSTRUMENT_ID;

CREATE OR REPLACE VIEW MART_FINANCE.VW_TRADE_LIFECYCLE AS
SELECT
  t.TRADE_ID,
  t.INSTRUMENT_ID,
  t.BUYER_LEI,
  buyer.LEGAL_NAME AS BUYER_NAME,
  t.SELLER_LEI,
  seller.LEGAL_NAME AS SELLER_NAME,
  t.BROKER_LEI,
  broker.LEGAL_NAME AS BROKER_NAME,
  t.COUNTERPARTY_LEI,
  cpty.LEGAL_NAME AS COUNTERPARTY_NAME,
  t.TRADE_DATE,
  t.SETTLEMENT_DATE,
  DATEDIFF('day', t.TRADE_DATE, t.SETTLEMENT_DATE) AS SETTLEMENT_LAG_DAYS,
  t.TRADE_STATUS,
  t.SIDE,
  t.QUANTITY,
  t.PRICE,
  t.NOTIONAL_AMOUNT_USD,
  t.COMMISSION_USD
FROM MART_FINANCE.TRADE t
LEFT JOIN MART_FINANCE.LEGAL_ENTITY buyer
  ON t.BUYER_LEI = buyer.LEI
LEFT JOIN MART_FINANCE.LEGAL_ENTITY seller
  ON t.SELLER_LEI = seller.LEI
LEFT JOIN MART_FINANCE.LEGAL_ENTITY broker
  ON t.BROKER_LEI = broker.LEI
LEFT JOIN MART_FINANCE.LEGAL_ENTITY cpty
  ON t.COUNTERPARTY_LEI = cpty.LEI;

CREATE OR REPLACE VIEW MART_FINANCE.VW_EXPOSURE_BY_COUNTERPARTY AS
SELECT
  e.EXPOSURE_ID,
  e.INSTRUMENT_ID,
  i.INSTRUMENT_TYPE,
  i.ISSUER_LEI,
  i.ISSUER_NAME,
  e.COUNTERPARTY_LEI,
  cpty.LEGAL_NAME AS COUNTERPARTY_NAME,
  cpty.JURISDICTION AS COUNTERPARTY_JURISDICTION,
  e.EXPOSURE_DATE,
  e.EXPOSURE_TYPE,
  e.EXPOSURE_AMOUNT_USD,
  e.VAR_95_1D_USD,
  e.DURATION_YEARS,
  e.CREDIT_RATING,
  e.RISK_MODEL_VERSION
FROM MART_FINANCE.RISK_EXPOSURE e
LEFT JOIN MART_FINANCE.VW_INSTRUMENT_ENRICHED i
  ON e.INSTRUMENT_ID = i.INSTRUMENT_ID
LEFT JOIN MART_FINANCE.LEGAL_ENTITY cpty
  ON e.COUNTERPARTY_LEI = cpty.LEI;

